#ifndef STANDALONE_STANDALONETRANSFORMS_UTILS_H
#define STANDALONE_STANDALONETRANSFORMS_UTILS_H

#include <string>

std::string unmangleUfName(std::string ufMangledName);

#endif // STANDALONE_STANDALONETRANSFORMS_UTILS_H